version: "3"
services:
  redis:
    image: redis
    ports: 
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data
  nginx:
    image: nginx
    ports: 
      - "8080:80"

volumes:
  redis:
