version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.6.4 # every job must define an image for the docker executor and subsequent jobs may define a different image.
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          command: |  # use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install -d
      - run:
          command: cd ~/project/src && pipenv run pylint *.py lib
      - run:
          command: cd ~/project/src && pipenv run black --check .
