version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.3 # every job must define an image for the docker executor and subsequent jobs may define a different image.
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          name: Prep cache
          command: sudo chown -R circleci:circleci /usr/local/bin ; sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: pipdeps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install pip dependencies
          command: |  # use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install -d
      - save_cache:
          key: pipdeps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - run:
          name: PyLint
          command: cd ~/project/src && pipenv run pylint src
      - run:
          name: Black
          command: cd ~/project/src && pipenv run black --check .
